### PR TITLE
Swapped to use Semantic UI tabs, added group-tabs and code-tabs

### PR DESCRIPTION
**Pull request by dmed256**
I'm not super familiar with the use of `setup.py` to test sphinx_tabs locally

I believe this should work but I would like to test it first

What do you do to test it locally?

Thanks

### CODE REVIEW

**Comment by djungelorm** [comment]
To test locally, I set up a virtualenv, then run `make install test`. This runs pylint and pep8 checks, then builds `test/index.rst`. The result is output to `test-output/index.html`, which I just manually check in a browser. Travis CI is just set up to run the same thing, although obviously doesn't check the output in a browser... Looks like your changes pass those automated tests :)

You'll want to add some examples of group-tabs and code-tabs to `test/index.rst` as well.

**Comment by dmed256** [comment]
Ah thanks!
I'll try it out tonight

**Comment by dmed256** [comment]
Added tests which pass when testing locally

I also removed the whole Semantic UI as a dependency and only depend on the few files we need for tabs. Styling fights between Sphinx and Semantic UI was becoming an issue > .<

If this is good, could you let me know when you update the package so I can depend on it ;)

**Comment by dmed256** [comment]
Eh actually, let me add some screenshots for the README first 👍

**Comment by djungelorm** [comment]
Awesome work - thanks :D

v0.2.0 has been uploaded to pypi

**Comment by dmed256** [comment]
Thanks for updating the pypi package to 0.2.0!
Hmm, I'm having issues with the _static files on readthedocs but not locally

```
http://occa.readthedocs.io/en/latest/_static/sphinx_tabs/tabs.css Failed to load resource: the server responded with a status of 404 (OK)
```

Any clues?

**Pull request merged**
